
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      # build image
      - run: |
          docker info
          docker build -t aspnetapp -f Dockerfile .
      # deploy the image
      - run: |
          docker login --username=gevorg.kesyan@mail.ru --password=1234QWer. registry.heroku.com
          docker tag aspnetapp registry.heroku.com/smartretailapp/web
          docker push registry.heroku.com/smartretailapp/web                
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku container:release web -a smartretailapp